version: '3.3'

services:  
  business-keyman:
    container_name: business-keyman
    build: .
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: npm run start
