export interface ITimezones {
    abbr: string;
    offset: number;
    isdst: boolean;
    utc: string[];
    ru_names: string[];
    text: string;
    value: string;
}

export const Timezones: ITimezones[] = [
    {
        abbr: 'DST',
        offset: -12,
        isdst: false,
        utc: ['Etc/GMT+12'],
        ru_names: [],
        text: '(UTC-12:00) International Date Line West',
        value: 'Dateline Standard Time',
    },
    {
        abbr: 'U',
        offset: -11,
        isdst: false,
        utc: [
            'Etc/GMT+11',
            'Pacific/Midway',
            'Pacific/Niue',
            'Pacific/Pago_Pago',
        ],
        ru_names: [
            'Паго Паго, Соединенные Штаты Америки (США)',
            'Алофи, остров Ниуе',
        ],
        text: '(UTC-11:00) Coordinated Universal Time-11',
        value: 'UTC-11',
    },
    {
        abbr: 'HST',
        offset: -10,
        isdst: false,
        utc: [
            'Etc/GMT+10',
            'Pacific/Honolulu',
            'Pacific/Johnston',
            'Pacific/Rarotonga',
            'Pacific/Tahiti',
        ],
        ru_names: [
            'Папеэте, Французская Полинезия',
            'Гонолулу, Соединенные Штаты Америки (США)',
            'Раротонга, Острова Куку',
        ],
        text: '(UTC-10:00) Hawaii',
        value: 'Hawaiian Standard Time',
    },
    {
        abbr: 'AKDT',
        offset: -8,
        isdst: true,
        utc: [
            'America/Anchorage',
            'America/Juneau',
            'America/Nome',
            'America/Sitka',
            'America/Yakutat',
        ],
        ru_names: [
            'Анкоридж, Соединенные Штаты Америки (США)',
            'Джуно, Соединенные Штаты Америки (США)',
            'Фэрбенкс, Соединенные Штаты Америки (США)',
            'Ном, Соединенные Штаты Америки (США)',
        ],
        text: '(UTC-09:00) Alaska',
        value: 'Alaskan Standard Time',
    },
    {
        abbr: 'PDT',
        offset: -7,
        isdst: true,
        utc: ['America/Santa_Isabel'],
        ru_names: [],
        text: '(UTC-08:00) Baja California',
        value: 'Pacific Standard Time (Mexico)',
    },
    {
        abbr: 'PDT',
        offset: -7,
        isdst: true,
        utc: [
            'America/Dawson',
            'America/Los_Angeles',
            'America/Tijuana',
            'America/Vancouver',
            'America/Whitehorse',
        ],
        ru_names: [
            'Портленд, Соединенные Штаты Америки (США)',
            'Анахейм, Соединенные Штаты Америки (США)',
            'Риверсайд, Соединенные Штаты Америки (США)',
            'Сакраменто, Соединенные Штаты Америки (США)',
            'Салем, Соединенные Штаты Америки (США)',
            'Сан-Диего, Соединенные Штаты Америки (США)',
            'Сан Франциско, Соединенные Штаты Америки (США)',
            'Сан-Хосе (Калифорния), Соединенные Штаты Америки (США)',
            'Лас-Вегас, Соединенные Штаты Америки (США)',
            'Сиэтл, Соединенные Штаты Америки (США)',
            'Лонг Бич, Соединенные Штаты Америки (США)',
            'Лос-Анджелес, Соединенные Штаты Америки (США)',
            'Карсон-Сити, Соединенные Штаты Америки (США)',
            'Стокон, Соединенные Штаты Америки (США)',
            'Сюррей, Канада',
            'Тихуана, Мексика',
            'Мехикали, Мексика',
            'Ванкувер, Канада',
            'Виктория (Канада), Канада',
            'Уайтхорс, Канада',
            'Окленд, Соединенные Штаты Америки (США)',
        ],
        text: '(UTC-07:00) Pacific Time (US & Canada)',
        value: 'Pacific Daylight Time',
    },
    {
        abbr: 'PST',
        offset: -8,
        isdst: false,
        utc: [
            'America/Dawson',
            'America/Los_Angeles',
            'America/Tijuana',
            'America/Vancouver',
            'America/Whitehorse',
            'PST8PDT',
        ],
        ru_names: [
            'Портленд, Соединенные Штаты Америки (США)',
            'Анахейм, Соединенные Штаты Америки (США)',
            'Риверсайд, Соединенные Штаты Америки (США)',
            'Сакраменто, Соединенные Штаты Америки (США)',
            'Салем, Соединенные Штаты Америки (США)',
            'Сан-Диего, Соединенные Штаты Америки (США)',
            'Сан Франциско, Соединенные Штаты Америки (США)',
            'Сан-Хосе (Калифорния), Соединенные Штаты Америки (США)',
            'Лас-Вегас, Соединенные Штаты Америки (США)',
            'Сиэтл, Соединенные Штаты Америки (США)',
            'Лонг Бич, Соединенные Штаты Америки (США)',
            'Лос-Анджелес, Соединенные Штаты Америки (США)',
            'Карсон-Сити, Соединенные Штаты Америки (США)',
            'Стокон, Соединенные Штаты Америки (США)',
            'Сюррей, Канада',
            'Тихуана, Мексика',
            'Мехикали, Мексика',
            'Ванкувер, Канада',
            'Виктория (Канада), Канада',
            'Уайтхорс, Канада',
            'Окленд, Соединенные Штаты Америки (США)',
        ],
        text: '(UTC-08:00) Pacific Time (US & Canada)',
        value: 'Pacific Standard Time',
    },
    {
        abbr: 'UMST',
        offset: -7,
        isdst: false,
        utc: [
            'America/Creston',
            'America/Dawson_Creek',
            'America/Hermosillo',
            'America/Phoenix',
            'Etc/GMT+7',
        ],
        ru_names: [
            'Феникс, Соединенные Штаты Америки (США)',
            'Меса, Соединенные Штаты Америки (США)',
            'Туксон, Соединенные Штаты Америки (США)',
        ],
        text: '(UTC-07:00) Arizona',
        value: 'US Mountain Standard Time',
    },
    {
        abbr: 'MDT',
        offset: -6,
        isdst: true,
        utc: ['America/Chihuahua', 'America/Mazatlan'],
        ru_names: ['Чиуауа, Мексика', 'Мацатлан, Мексика'],
        text: '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
        value: 'Mountain Standard Time (Mexico)',
    },
    {
        abbr: 'MDT',
        offset: -6,
        isdst: true,
        utc: [
            'America/Boise',
            'America/Cambridge_Bay',
            'America/Denver',
            'America/Edmonton',
            'America/Inuvik',
            'America/Ojinaga',
            'America/Yellowknife',
            'MST7MDT',
        ],
        ru_names: [
            'Хелена, Соединенные Штаты Америки (США)',
            'Аклавик, Канада',
            'Альбукерке, Соединенные Штаты Америки (США)',
            'Аврора, Соединенные Штаты Америки (США)',
            'Солт-Лейк-Сити, Соединенные Штаты Америки (США)',
            'Биллингс, Соединенные Штаты Америки (США)',
            'Бойсе, Соединенные Штаты Америки (США)',
            'Санта-Фе, Соединенные Штаты Америки (США)',
            'Калгари, Канада',
            'Шайенн, Соединенные Штаты Америки (США)',
            'Денвер, Соединенные Штаты Америки (США)',
            'Эдмонтон, Канада',
            'Эль Пасо, Соединенные Штаты Америки (США)',
            'Йеллоунайф, Канада',
        ],
        text: '(UTC-07:00) Mountain Time (US & Canada)',
        value: 'Mountain Standard Time',
    },
    {
        abbr: 'CAST',
        offset: -6,
        isdst: false,
        utc: [
            'America/Belize',
            'America/Costa_Rica',
            'America/El_Salvador',
            'America/Guatemala',
            'America/Managua',
            'America/Tegucigalpa',
            'Etc/GMT+6',
            'Pacific/Galapagos',
        ],
        ru_names: [
            'Бельмопан, Белиз',
            'Сан-Хосе (Коста-Рика), Коста-Рика',
            'Сан Сальвадор, Сальвадор',
            'Санта Анна, Сальвадор',
            'Манагуа, Никарагуа',
            'Тегусигальпа, Гондурас',
            'Галапагосские острова, Еквадор',
            'Гватемала, Гватемала',
        ],
        text: '(UTC-06:00) Central America',
        value: 'Central America Standard Time',
    },
    {
        abbr: 'CDT',
        offset: -5,
        isdst: true,
        utc: [
            'America/Chicago',
            'America/Indiana/Knox',
            'America/Indiana/Tell_City',
            'America/Matamoros',
            'America/Menominee',
            'America/North_Dakota/Beulah',
            'America/North_Dakota/Center',
            'America/North_Dakota/New_Salem',
            'America/Rainy_River',
            'America/Rankin_Inlet',
            'America/Resolute',
            'America/Winnipeg',
            'CST6CDT',
        ],
        ru_names: [
            'Пенсакола, Соединенные Штаты Америки (США)',
            'Хьюстон, Соединенные Штаты Америки (США)',
            'Пирр, Соединенные Штаты Америки (США)',
            'Джексон, Соединенные Штаты Америки (США)',
            'Джефферсон-Сити, Соединенные Штаты Америки (США)',
            'Арлингтон, Соединенные Штаты Америки (США)',
            'Канзас, Соединенные Штаты Америки (США)',
            'Остин, Соединенные Штаты Америки (США)',
            'Батон-Руж, Соединенные Штаты Америки (США)',
            'Сан Антонио, Соединенные Штаты Америки (США)',
            'Бирмингем  (USA), Соединенные Штаты Америки (США)',
            'Бисмарк, Соединенные Штаты Америки (США)',
            'Линкольн, Соединенные Штаты Америки (США)',
            'Литл-Рок, Соединенные Штаты Америки (США)',
            'Су-Фолс, Соединенные Штаты Америки (США)',
            'Сент-Луис, Соединенные Штаты Америки (США)',
            'Сен-Поль, Соединенные Штаты Америки (США)',
            'Мэдисон, Соединенные Штаты Америки (США)',
            'Чикаго, Соединенные Штаты Америки (США)',
            'Даллас, Соединенные Штаты Америки (США)',
            'Мемфис, Соединенные Штаты Америки (США)',
            'Де-Мойн, Соединенные Штаты Америки (США)',
            'Топека, Соединенные Штаты Америки (США)',
            'Милуоки, Соединенные Штаты Америки (США)',
            'Миннеаполис, Соединенные Штаты Америки (США)',
            'Мобил, Соединенные Штаты Америки (США)',
            'Монтгомери, Соединенные Штаты Америки (США)',
            'Форт-Уэрт, Соединенные Штаты Америки (США)',
            'Нэшвилл, Соединенные Штаты Америки (США)',
            'Новый Орлеан, Соединенные Штаты Америки (США)',
            'Уичита, Соединенные Штаты Америки (США)',
            'Виннипег, Канада',
            'Оклахома Сити, Соединенные Штаты Америки (США)',
        ],
        text: '(UTC-06:00) Central Time (US & Canada)',
        value: 'Central Standard Time',
    },
    {
        abbr: 'CDT',
        offset: -5,
        isdst: true,
        utc: [
            'America/Bahia_Banderas',
            'America/Cancun',
            'America/Merida',
            'America/Mexico_City',
            'America/Monterrey',
        ],
        ru_names: [
            'Акапулько, Мексика',
            'Агуаскальентес, Мексика',
            'Сан-Луис-Потоси, Мексика',
            'Леон, Мексика',
            'Канкун, Мексика',
            'Мерида, Мексика',
            'Мехико, Мексика',
            'Монтеррей, Мексика',
            'Веракруз, Мексика',
            'Гвадалахара, Мексика',
        ],
        text: '(UTC-06:00) Guadalajara, Mexico City, Monterrey',
        value: 'Central Standard Time (Mexico)',
    },
    {
        abbr: 'CCST',
        offset: -6,
        isdst: false,
        utc: ['America/Regina', 'America/Swift_Current'],
        ru_names: ['Регина, Канада'],
        text: '(UTC-06:00) Saskatchewan',
        value: 'Canada Central Standard Time',
    },
    {
        abbr: 'SPST',
        offset: -5,
        isdst: false,
        utc: [
            'America/Bogota',
            'America/Cayman',
            'America/Coral_Harbour',
            'America/Eirunepe',
            'America/Guayaquil',
            'America/Jamaica',
            'America/Lima',
            'America/Panama',
            'America/Rio_Branco',
            'Etc/GMT+5',
        ],
        ru_names: [
            'Панама, Панама',
            'Кито, Еквадор',
            'Риу-Бранку, Бразилия',
            'Кингстон (Jm), Ямайка',
            'Богота, Колумбия',
            'Лима, Перу',
            'Кали, Колумбия',
            'Меделин, Колумбия',
            'Джорджтаун (KY), Кайманские острова',
            'Гуаякиль, Еквадор',
        ],
        text: '(UTC-05:00) Bogota, Lima, Quito',
        value: 'SA Pacific Standard Time',
    },
    {
        abbr: 'EDT',
        offset: -4,
        isdst: true,
        utc: [
            'America/Detroit',
            'America/Havana',
            'America/Indiana/Petersburg',
            'America/Indiana/Vincennes',
            'America/Indiana/Winamac',
            'America/Iqaluit',
            'America/Kentucky/Monticello',
            'America/Louisville',
            'America/Montreal',
            'America/Nassau',
            'America/New_York',
            'America/Nipigon',
            'America/Pangnirtung',
            'America/Port-au-Prince',
            'America/Thunder_Bay',
            'America/Toronto',
            'EST5EDT',
        ],
        ru_names: [
            'Гаррисберг, Соединенные Штаты Америки (США)',
            'Хартфорд, Соединенные Штаты Америки (США)',
            'Гавана, Куба',
            'Филадельфия, Соединенные Штаты Америки (США)',
            'Акрон, Соединенные Штаты Америки (США)',
            'Олбани, Соединенные Штаты Америки (США)',
            'Питсбург, Соединенные Штаты Америки (США)',
            'Икалуит, Канада',
            'Порт-о-Пренс, Гаити',
            'Джексонвиль, Соединенные Штаты Америки (США)',
            'Джерси-Сити, Соединенные Штаты Америки (США)',
            'Провиденс, Соединенные Штаты Америки (США)',
            'Квебек, Канада',
            'Атланта, Соединенные Штаты Америки (США)',
            'Августа, Соединенные Штаты Америки (США)',
            'Рали, Соединенные Штаты Америки (США)',
            'Ричмонд, Соединенные Штаты Америки (США)',
            'Балтимор, Соединенные Штаты Америки (США)',
            'Рочестер, Соединенные Штаты Америки (США)',
            'Ноксвиль, Соединенные Штаты Америки (США)',
            'Бостон, Соединенные Штаты Америки (США)',
            'Лексингтон, Соединенные Штаты Америки (США)',
            'Буфало, Соединенные Штаты Америки (США)',
            'Сент-Питерсберг (Флорида), Соединенные Штаты Америки (США)',
            'Чарлстон, Соединенные Штаты Америки (США)',
            'Шарлот, Соединенные Штаты Америки (США)',
            'Цинциннати, Соединенные Штаты Америки (США)',
            'Тампа, Соединенные Штаты Америки (США)',
            'Кливленд, Соединенные Штаты Америки (США)',
            'Коламбия, Соединенные Штаты Америки (США)',
            'Коламбус, Соединенные Штаты Америки (США)',
            'Конкорд, Соединенные Штаты Америки (США)',
            'Майами, Соединенные Штаты Америки (США)',
            'Толедо, Соединенные Штаты Америки (США)',
            'Детройт, Соединенные Штаты Америки (США)',
            'Торонто, Канада',
            'Трентон, Соединенные Штаты Америки (США)',
            'Довер, Соединенные Штаты Америки (США)',
            'Монпелье, Соединенные Штаты Америки (США)',
            'Монреаль, Канада',
            'Франкфорт (США), Соединенные Штаты Америки (США)',
            'Нассау, Багамские острова',
            'Вирджиния Бич, Соединенные Штаты Америки (США)',
            'Нью-Йорк, Соединенные Штаты Америки (США)',
            'Ньюарк, Соединенные Штаты Америки (США)',
            'Вашингтон, Соединенные Штаты Америки (США)',
            'Остров Норфолк, Соединенные Штаты Америки (США)',
            'Оттава, Канада',
            'Вест Палм Бич, Соединенные Штаты Америки (США)',
        ],
        text: '(UTC-05:00) Eastern Time (US & Canada)',
        value: 'Eastern Standard Time',
    },
    {
        abbr: 'UEDT',
        offset: -4,
        isdst: true,
        utc: [
            'America/Indiana/Marengo',
            'America/Indiana/Vevay',
            'America/Indianapolis',
        ],
        ru_names: [],
        text: '(UTC-05:00) Indiana (East)',
        value: 'US Eastern Standard Time',
    },
    {
        abbr: 'VST',
        offset: -4.5,
        isdst: false,
        utc: ['America/Caracas'],
        ru_names: ['Каракас, Венесуэла'],
        text: '(UTC-04:30) Caracas',
        value: 'Venezuela Standard Time',
    },
    {
        abbr: 'PYT',
        offset: -4,
        isdst: false,
        utc: ['America/Asuncion'],
        ru_names: ['Асунсьон, Парагвай'],
        text: '(UTC-04:00) Asuncion',
        value: 'Paraguay Standard Time',
    },
    {
        abbr: 'ADT',
        offset: -3,
        isdst: true,
        utc: [
            'America/Glace_Bay',
            'America/Goose_Bay',
            'America/Halifax',
            'America/Moncton',
            'America/Thule',
            'Atlantic/Bermuda',
        ],
        ru_names: [
            'Сент-Джонс (CA - NB), Канада',
            'Чарлеттаун, Канада',
            'Галифакс, Канада',
            'Гамильтон, Бермудские острова',
        ],
        text: '(UTC-04:00) Atlantic Time (Canada)',
        value: 'Atlantic Standard Time',
    },
    {
        abbr: 'CBST',
        offset: -4,
        isdst: false,
        utc: ['America/Campo_Grande', 'America/Cuiaba'],
        ru_names: [],
        text: '(UTC-04:00) Cuiaba',
        value: 'Central Brazilian Standard Time',
    },
    {
        abbr: 'SWST',
        offset: -4,
        isdst: false,
        utc: [
            'America/Anguilla',
            'America/Antigua',
            'America/Aruba',
            'America/Barbados',
            'America/Blanc-Sablon',
            'America/Boa_Vista',
            'America/Curacao',
            'America/Dominica',
            'America/Grand_Turk',
            'America/Grenada',
            'America/Guadeloupe',
            'America/Guyana',
            'America/Kralendijk',
            'America/La_Paz',
            'America/Lower_Princes',
            'America/Manaus',
            'America/Marigot',
            'America/Martinique',
            'America/Montserrat',
            'America/Port_of_Spain',
            'America/Porto_Velho',
            'America/Puerto_Rico',
            'America/Santo_Domingo',
            'America/St_Barthelemy',
            'America/St_Kitts',
            'America/St_Lucia',
            'America/St_Thomas',
            'America/St_Vincent',
            'America/Tortola',
            'Etc/GMT+4',
        ],
        ru_names: [
            'Плимут, Монтсеррат',
            'Порт-оф-Спейн, Тринидад и Тобаго',
            'Род-Таун, Британские Виргинские острова',
            'Кингстаун, Сент-Винсент и Гренадины',
            'Розо, Доминика',
            'Бас-Тер, Гваделупа',
            'Бастер, Сент-Китс и Невис',
            'Сент-Джорджес, Гренада',
            'Сент-Джонс (Антигуа), Антигуа и Барбуда',
            'Ла Пас, Боливия',
            'Сан Хуан, Пуэрто-Рико',
            'Бриджтаун, Барбадос',
            'Санто Доминго, Доминиканская Республика',
            'Кастри, Сент-Люсия',
            'Манаус, Бразилия',
            'Вэлли, Ангилья',
            'Фор-де-Франс, Мартиника',
            'Виллемстад, Нидерландские Антильские острова',
            'Джорджтаун (GY), Гаяна',
            'Ораньєстад, Аруба',
        ],
        text: '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan',
        value: 'SA Western Standard Time',
    },
    {
        abbr: 'PSST',
        offset: -4,
        isdst: false,
        utc: ['America/Santiago', 'Antarctica/Palmer'],
        ru_names: ['Сантьяго, Чили'],
        text: '(UTC-04:00) Santiago',
        value: 'Pacific SA Standard Time',
    },
    {
        abbr: 'NDT',
        offset: -2.5,
        isdst: true,
        utc: ['America/St_Johns'],
        ru_names: ['Сент Джон (CA - NF), Канада'],
        text: '(UTC-03:30) Newfoundland',
        value: 'Newfoundland Standard Time',
    },
    {
        abbr: 'ESAST',
        offset: -3,
        isdst: false,
        utc: ['America/Sao_Paulo'],
        ru_names: [
            'Порту-Алегри, Бразилия',
            'Рио-де-Жанейро, Бразилия',
            'Бразилиа, Бразилия',
            'Сан Пауло, Бразилия',
        ],
        text: '(UTC-03:00) Brasilia',
        value: 'E. South America Standard Time',
    },
    {
        abbr: 'AST',
        offset: -3,
        isdst: false,
        utc: [
            'America/Argentina/La_Rioja',
            'America/Argentina/Rio_Gallegos',
            'America/Argentina/Salta',
            'America/Argentina/San_Juan',
            'America/Argentina/San_Luis',
            'America/Argentina/Tucuman',
            'America/Argentina/Ushuaia',
            'America/Buenos_Aires',
            'America/Catamarca',
            'America/Cordoba',
            'America/Jujuy',
            'America/Mendoza',
        ],
        ru_names: ['Сальта, Аргентина', 'Тукуман, Аргентина'],
        text: '(UTC-03:00) Buenos Aires',
        value: 'Argentina Standard Time',
    },
    {
        abbr: 'SEST',
        offset: -3,
        isdst: false,
        utc: [
            'America/Araguaina',
            'America/Belem',
            'America/Cayenne',
            'America/Fortaleza',
            'America/Maceio',
            'America/Paramaribo',
            'America/Recife',
            'America/Santarem',
            'Antarctica/Rothera',
            'Atlantic/Stanley',
            'Etc/GMT+3',
        ],
        ru_names: [
            'Парамарибо, Суринам',
            'Ресифе, Бразилия',
            'Кайенна, Французская Гвиана',
            'Стенли, Фолклендские острова',
        ],
        text: '(UTC-03:00) Cayenne, Fortaleza',
        value: 'SA Eastern Standard Time',
    },
    {
        abbr: 'GDT',
        offset: -3,
        isdst: true,
        utc: ['America/Godthab'],
        ru_names: ['Нуук, Дания'],
        text: '(UTC-03:00) Greenland',
        value: 'Greenland Standard Time',
    },
    {
        abbr: 'MST',
        offset: -3,
        isdst: false,
        utc: ['America/Montevideo'],
        ru_names: ['Монтевидео, Уругвай'],
        text: '(UTC-03:00) Montevideo',
        value: 'Montevideo Standard Time',
    },
    {
        abbr: 'BST',
        offset: -3,
        isdst: false,
        utc: ['America/Bahia'],
        ru_names: ['Сальвадор, Бразилия'],
        text: '(UTC-03:00) Salvador',
        value: 'Bahia Standard Time',
    },
    {
        abbr: 'U',
        offset: -2,
        isdst: false,
        utc: ['America/Noronha', 'Atlantic/South_Georgia', 'Etc/GMT+2'],
        ru_names: ['Фернанду-ди-Норонья, Бразилия'],
        text: '(UTC-02:00) Coordinated Universal Time-02',
        value: 'UTC-02',
    },
    {
        abbr: 'MDT',
        offset: -1,
        isdst: true,
        utc: [],
        ru_names: [],
        text: '(UTC-02:00) Mid-Atlantic - Old',
        value: 'Mid-Atlantic Standard Time',
    },
    {
        abbr: 'ADT',
        offset: 0,
        isdst: true,
        utc: ['America/Scoresbysund', 'Atlantic/Azores'],
        ru_names: ['Азоры, Порутугалия'],
        text: '(UTC-01:00) Azores',
        value: 'Azores Standard Time',
    },
    {
        abbr: 'CVST',
        offset: -1,
        isdst: false,
        utc: ['Atlantic/Cape_Verde', 'Etc/GMT+1'],
        ru_names: ['Прая, Кабо-Верде'],
        text: '(UTC-01:00) Cape Verde Is.',
        value: 'Cape Verde Standard Time',
    },
    {
        abbr: 'MDT',
        offset: 1,
        isdst: true,
        utc: ['Africa/Casablanca', 'Africa/El_Aaiun'],
        ru_names: [
            'Рабат, Марокко',
            'Касабланка, Марокко',
            'Танжер, Марокко',
            'Эль-Аюн, Западная Сахара',
        ],
        text: '(UTC) Casablanca',
        value: 'Morocco Standard Time',
    },
    {
        abbr: 'UTC',
        offset: 0,
        isdst: false,
        utc: ['America/Danmarkshavn', 'Etc/GMT'],
        ru_names: [],
        text: '(UTC) Coordinated Universal Time',
        value: 'UTC',
    },
    {
        abbr: 'GMT',
        offset: 0,
        isdst: false,
        utc: [
            'Europe/Isle_of_Man',
            'Europe/Guernsey',
            'Europe/Jersey',
            'Europe/London',
        ],
        ru_names: [
            'Белфаст, Великобритания',
            'Бирмингем (UK), Великобритания',
            'Ливерпуль, Великобритания',
            'Лондон, Великобритания',
            'Кардифф, Великобритания',
            'Эдинбург, Великобритания',
            'Глазго, Великобритания',
        ],
        text: '(UTC) Edinburgh, London',
        value: 'Greenwich Mean Time',
    },
    {
        abbr: 'BST',
        offset: 1,
        isdst: true,
        utc: [
            'Europe/Isle_of_Man',
            'Europe/Guernsey',
            'Europe/Jersey',
            'Europe/London',
        ],
        ru_names: [
            'Белфаст, Великобритания',
            'Бирмингем (UK), Великобритания',
            'Ливерпуль, Великобритания',
            'Лондон, Великобритания',
            'Кардифф, Великобритания',
            'Эдинбург, Великобритания',
            'Глазго, Великобритания',
        ],
        text: '(UTC+01:00) Edinburgh, London',
        value: 'British Summer Time',
    },
    {
        abbr: 'GDT',
        offset: 1,
        isdst: true,
        utc: [
            'Atlantic/Canary',
            'Atlantic/Faeroe',
            'Atlantic/Madeira',
            'Europe/Dublin',
            'Europe/Lisbon',
        ],
        ru_names: [
            'Порту, Порутугалия',
            'Лас-Пальмас-де-Гран-Канария, Испания',
            'Лиссабон, Порутугалия',
            'Дублин, Ирландия',
            'Фуншал, Порутугалия',
        ],
        text: '(UTC) Dublin, Lisbon',
        value: 'GMT Standard Time',
    },
    {
        abbr: 'GST',
        offset: 0,
        isdst: false,
        utc: [
            'Africa/Abidjan',
            'Africa/Accra',
            'Africa/Bamako',
            'Africa/Banjul',
            'Africa/Bissau',
            'Africa/Conakry',
            'Africa/Dakar',
            'Africa/Freetown',
            'Africa/Lome',
            'Africa/Monrovia',
            'Africa/Nouakchott',
            'Africa/Ouagadougou',
            'Africa/Sao_Tome',
            'Atlantic/Reykjavik',
            'Atlantic/St_Helena',
        ],
        ru_names: [
            'Абиджан, Кот д’Ивуар',
            'Уагадугу, Буркина-Фасо',
            'Аккра, Гана',
            'Рейкьявик, Исландия',
            'Бамако, Мали',
            'Банжул, Гамбия',
            'Бисау, Гвиея Биссау',
            'Сан-Томе, Сан-Томе и Принсипи',
            'Ломе, Того',
            'Конакри, Гвинея',
            'Дакар, Сенегал',
            'Монровия, Либерия',
            'Фритаун, Сьерра-Леоне',
            'Нуакшот, Мавритания',
            'Ямусукро, Кот д’Ивуар',
        ],
        text: '(UTC) Monrovia, Reykjavik',
        value: 'Greenwich Standard Time',
    },
    {
        abbr: 'WEDT',
        offset: 2,
        isdst: true,
        utc: [
            'Arctic/Longyearbyen',
            'Europe/Amsterdam',
            'Europe/Andorra',
            'Europe/Berlin',
            'Europe/Busingen',
            'Europe/Gibraltar',
            'Europe/Luxembourg',
            'Europe/Malta',
            'Europe/Monaco',
            'Europe/Oslo',
            'Europe/Rome',
            'Europe/San_Marino',
            'Europe/Stockholm',
            'Europe/Vaduz',
            'Europe/Vatican',
            'Europe/Vienna',
            'Europe/Zurich',
        ],
        ru_names: [
            'Амстердам, Нидерланды',
            'Андорра-ла-Вьеха, Андорра',
            'Рим, Италия',
            'Роттердам, Нидерланды',
            'Берлин, Германия',
            'Берн, Швейцария',
            'Зальцбург, Австрия',
            'Сан-Марино, Сан-Марино',
            'Лозанна, Швейцария',
            'Люксембург, Люксембург',
            'Стокгольм, Швеция',
            'Милан, Италия',
            'Монако, Монако',
            'Турин, Италия',
            'Дюссельдорф, Германия',
            'Вадуц, Лихтенштейн',
            'Валлетта, Мальта',
            'Мюнхен, Германия',
            'Ватикан, Папский Престол',
            'Венеция, Италия',
            'Неаполь, Италия',
            'Вена, Австрия',
            'Франкфурт-на-Майне, Германия',
            'Женева, Швейцария',
            'Гибралтар, Гибралтар - Великобритания',
            'Гамбург, Германия',
            'Осло, Норвегия',
            'Цюрих, Швейцария',
        ],
        text: '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
        value: 'W. Europe Standard Time',
    },
    {
        abbr: 'CEDT',
        offset: 2,
        isdst: true,
        utc: [
            'Europe/Belgrade',
            'Europe/Bratislava',
            'Europe/Budapest',
            'Europe/Ljubljana',
            'Europe/Podgorica',
            'Europe/Prague',
            'Europe/Tirane',
        ],
        ru_names: [
            'Подгорица, Черногория',
            'Прага, Чехия',
            'Приштина, Сербия',
            'Белград, Сербия',
            'Братислава, Словакия',
            'Будапешт, Венгрия',
            'Любляна, Словения',
            'Тирана, Албания',
        ],
        text: '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
        value: 'Central Europe Standard Time',
    },
    {
        abbr: 'RDT',
        offset: 2,
        isdst: true,
        utc: [
            'Africa/Ceuta',
            'Europe/Brussels',
            'Europe/Copenhagen',
            'Europe/Madrid',
            'Europe/Paris',
        ],
        ru_names: [
            'Пальма-де-Мальорка, Испания',
            'Париж, Франция',
            'Барселона, Испания',
            'Бастия, Франция',
            'Ла-Корунья, Испания',
            'Брюссель, Бельгия',
            'Мадрид, Испания',
            'Копенгаген, Дания',
            'Кордоба, Испания',
            'Ницца, Франция',
        ],
        text: '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
        value: 'Romance Standard Time',
    },
    {
        abbr: 'CEDT',
        offset: 2,
        isdst: true,
        utc: [
            'Europe/Sarajevo',
            'Europe/Skopje',
            'Europe/Warsaw',
            'Europe/Zagreb',
        ],
        ru_names: [
            'Познань, Польша',
            'Краков, Польша',
            'Сараево, Босния и Герцеговина',
            'Лодзь, Польша',
            'Скопье, Македония',
            'Щецин, Польша',
            'Варшава, Польша',
            'Гданьск, Польша',
            'Вроцлав, Польша',
            'Загреб, Хорватия',
        ],
        text: '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
        value: 'Central European Standard Time',
    },
    {
        abbr: 'WCAST',
        offset: 1,
        isdst: false,
        utc: [
            'Africa/Algiers',
            'Africa/Bangui',
            'Africa/Brazzaville',
            'Africa/Douala',
            'Africa/Kinshasa',
            'Africa/Lagos',
            'Africa/Libreville',
            'Africa/Luanda',
            'Africa/Malabo',
            'Africa/Ndjamena',
            'Africa/Niamey',
            'Africa/Porto-Novo',
            'Africa/Tunis',
            'Etc/GMT-1',
        ],
        ru_names: [
            'Абуджа, Нигерия',
            'Алжир, Алжир',
            'Порто-Ново, Бенин',
            'Кано, Нигерия',
            'Банги, Центрально-Африканская Республика',
            'Киншаса, Демократическая Республика Конго',
            'Лагос, Нигерия',
            'Браззавиль, Конго',
            'Либревиль, Габон',
            'Луанда, Ангола',
            'Малабо, Екваториальная Гвинея',
            'Тунис, Тунис',
            'Нджамена, Чад',
            'Ниамей, Нигер',
            'Яунде, Камерун',
        ],
        text: '(UTC+01:00) West Central Africa',
        value: 'W. Central Africa Standard Time',
    },
    {
        abbr: 'NST',
        offset: 1,
        isdst: false,
        utc: ['Africa/Windhoek'],
        ru_names: ['Виндхук, Намибия'],
        text: '(UTC+01:00) Windhoek',
        value: 'Namibia Standard Time',
    },
    {
        abbr: 'GDT',
        offset: 3,
        isdst: true,
        utc: [
            'Asia/Nicosia',
            'Europe/Athens',
            'Europe/Bucharest',
            'Europe/Chisinau',
        ],
        ru_names: [
            'Афины, Греция',
            'Кишинев, Молдова',
            'Бухарест, Румыния',
            'Никосия, Кипр',
        ],
        text: '(UTC+02:00) Athens, Bucharest',
        value: 'GTB Standard Time',
    },
    {
        abbr: 'MEDT',
        offset: 3,
        isdst: true,
        utc: ['Asia/Beirut'],
        ru_names: ['Бейрут, Ливан'],
        text: '(UTC+02:00) Beirut',
        value: 'Middle East Standard Time',
    },
    {
        abbr: 'EST',
        offset: 2,
        isdst: false,
        utc: ['Africa/Cairo'],
        ru_names: ['Гиза, Египет', 'Александрия, Египет', 'Каир, Египет'],
        text: '(UTC+02:00) Cairo',
        value: 'Egypt Standard Time',
    },
    {
        abbr: 'SDT',
        offset: 3,
        isdst: true,
        utc: ['Asia/Damascus'],
        ru_names: ['Дамаск, Сирия'],
        text: '(UTC+02:00) Damascus',
        value: 'Syria Standard Time',
    },
    {
        abbr: 'EEDT',
        offset: 3,
        isdst: true,
        utc: [
            'Asia/Nicosia',
            'Europe/Athens',
            'Europe/Bucharest',
            'Europe/Chisinau',
            'Europe/Helsinki',
            'Europe/Kiev',
            'Europe/Mariehamn',
            'Europe/Nicosia',
            'Europe/Riga',
            'Europe/Sofia',
            'Europe/Tallinn',
            'Europe/Uzhgorod',
            'Europe/Vilnius',
            'Europe/Zaporozhye',
        ],
        ru_names: [
            'Хельсинки, Финляндия',
            'Афины, Греция',
            'Каунас, Литва',
            'Рига, Латвия',
            'Кишинев, Молдова',
            'Киев, Украина',
            'Бухарест, Румыния',
            'София, Болгария',
            'Таллин, Естония',
            'Вильнюс, Литва',
            'Никосия, Кипр',
            'Одесса, Украина',
        ],
        text: '(UTC+02:00) E. Europe',
        value: 'E. Europe Standard Time',
    },
    {
        abbr: 'SAST',
        offset: 2,
        isdst: false,
        utc: [
            'Africa/Blantyre',
            'Africa/Bujumbura',
            'Africa/Gaborone',
            'Africa/Harare',
            'Africa/Johannesburg',
            'Africa/Kigali',
            'Africa/Lubumbashi',
            'Africa/Lusaka',
            'Africa/Maputo',
            'Africa/Maseru',
            'Africa/Mbabane',
            'Etc/GMT-2',
        ],
        ru_names: [
            'Хараре, Зимбабве',
            'Претория, Южная Африка (Южно-Африканская республика)',
            'Йоханнесбург, Южная Африка (Южно-Африканская республика)',
            'Кигали, Руанда',
            'Лилонгве, Малави',
            'Бужумбура, Бурунди',
            'Кейптаун, Южная Африка (Южно-Африканская республика)',
            'Лубумбаши, Демократическая Республика Конго',
            'Лусака, Замбия',
            'Мапуту, Мозамбик',
            'Масеру, Лесото',
            'Мбабане, Свазиленд',
            'Габороне, Ботсвана',
        ],
        text: '(UTC+02:00) Harare, Pretoria',
        value: 'South Africa Standard Time',
    },
    {
        abbr: 'FDT',
        offset: 3,
        isdst: true,
        utc: [
            'Europe/Helsinki',
            'Europe/Kiev',
            'Europe/Mariehamn',
            'Europe/Riga',
            'Europe/Sofia',
            'Europe/Tallinn',
            'Europe/Uzhgorod',
            'Europe/Vilnius',
            'Europe/Zaporozhye',
        ],
        ru_names: [
            'Хельсинки, Финляндия',
            'Каунас, Литва',
            'Рига, Латвия',
            'Киев, Украина',
            'София, Болгария',
            'Таллин, Естония',
            'Вильнюс, Литва',
            'Одесса, Украина',
        ],
        text: '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
        value: 'FLE Standard Time',
    },
    {
        abbr: 'TDT',
        offset: 3,
        isdst: false,
        utc: ['Europe/Istanbul'],
        ru_names: ['Стамбул, Турция', 'Измир, Турция', 'Анкара, Турция'],
        text: '(UTC+03:00) Istanbul',
        value: 'Turkey Standard Time',
    },
    {
        abbr: 'JDT',
        offset: 3,
        isdst: true,
        utc: ['Asia/Jerusalem'],
        ru_names: ['Иерусалим, Израиль', 'Тель-Авив, Израиль'],
        text: '(UTC+02:00) Jerusalem',
        value: 'Israel Standard Time',
    },
    {
        abbr: 'LST',
        offset: 2,
        isdst: false,
        utc: ['Africa/Tripoli'],
        ru_names: ['Триполи, Ливия'],
        text: '(UTC+02:00) Tripoli',
        value: 'Libya Standard Time',
    },
    {
        abbr: 'JST',
        offset: 3,
        isdst: false,
        utc: ['Asia/Amman'],
        ru_names: ['Амман, Иордания'],
        text: '(UTC+03:00) Amman',
        value: 'Jordan Standard Time',
    },
    {
        abbr: 'AST',
        offset: 3,
        isdst: false,
        utc: ['Asia/Baghdad'],
        ru_names: ['Багдад, Ирак', 'Басра, Ирак'],
        text: '(UTC+03:00) Baghdad',
        value: 'Arabic Standard Time',
    },
    {
        abbr: 'KST',
        offset: 3,
        isdst: false,
        utc: ['Europe/Kaliningrad', 'Europe/Minsk'],
        ru_names: ['Калининград, Россия', 'Минск, Беларусь'],
        text: '(UTC+03:00) Kaliningrad, Minsk',
        value: 'Kaliningrad Standard Time',
    },
    {
        abbr: 'AST',
        offset: 3,
        isdst: false,
        utc: [
            'Asia/Aden',
            'Asia/Bahrain',
            'Asia/Kuwait',
            'Asia/Qatar',
            'Asia/Riyadh',
        ],
        ru_names: [
            'Аден, Йемен (Йеменская Арабская Республика)',
            'Джидда, Саудовская Аравия',
            'Эр-Рияд, Саудовская Аравия',
            'Кувейт, Кувейт',
            'Сана, Йемен (Йеменская Арабская Республика)',
            'Мекка, Саудовская Аравия',
            'Манама, Бахрейн',
            'Доха, Катар',
        ],
        text: '(UTC+03:00) Kuwait, Riyadh',
        value: 'Arab Standard Time',
    },
    {
        abbr: 'EAST',
        offset: 3,
        isdst: false,
        utc: [
            'Africa/Addis_Ababa',
            'Africa/Asmera',
            'Africa/Dar_es_Salaam',
            'Africa/Djibouti',
            'Africa/Juba',
            'Africa/Kampala',
            'Africa/Khartoum',
            'Africa/Mogadishu',
            'Africa/Nairobi',
            'Antarctica/Syowa',
            'Etc/GMT-3',
            'Indian/Antananarivo',
            'Indian/Comoro',
            'Indian/Mayotte',
        ],
        ru_names: [
            'Аддис-Абеба, Ефиопия',
            'Антананариву, Мадагаскар',
            'Кампала, Уганда',
            'Хартум, Судан',
            'Мамудзу, Майотта',
            'Дар-эс-Салам, Танзания',
            'Джибути, Джибутти',
            'Додома, Танзания',
            'Могадишу, Сомали',
            'Морони, Коморские острова',
            'Найроби, Кения',
            'Джуба, Южный Судан',
        ],
        text: '(UTC+03:00) Nairobi',
        value: 'E. Africa Standard Time',
    },
    {
        abbr: 'MSK',
        offset: 3,
        isdst: false,
        utc: [
            'Europe/Kirov',
            'Europe/Moscow',
            'Europe/Simferopol',
            'Europe/Volgograd',
        ],
        ru_names: [
            'Казань, Россия',
            'Санкт-Петербург, Россия',
            'Москва, Россия',
            'Мурманск, Россия',
            'Новгород, Россия',
        ],
        text: '(UTC+03:00) Moscow, St. Petersburg, Volgograd',
        value: 'Moscow Standard Time',
    },
    {
        abbr: 'SAMT',
        offset: 4,
        isdst: false,
        utc: ['Europe/Astrakhan', 'Europe/Samara', 'Europe/Ulyanovsk'],
        ru_names: ['Самара, Россия'],
        text: '(UTC+04:00) Samara, Ulyanovsk, Saratov',
        value: 'Samara Time',
    },
    {
        abbr: 'IDT',
        offset: 4.5,
        isdst: true,
        utc: ['Asia/Tehran'],
        ru_names: ['Тегеран, Иран', 'Исфахан, Иран'],
        text: '(UTC+03:30) Tehran',
        value: 'Iran Standard Time',
    },
    {
        abbr: 'AST',
        offset: 4,
        isdst: false,
        utc: ['Asia/Dubai', 'Asia/Muscat', 'Etc/GMT-4'],
        ru_names: [
            'Абу-Даби, Объединенные Арабские Эмираты',
            'Дубай, Объединенные Арабские Эмираты',
            'Маскат, Оман',
        ],
        text: '(UTC+04:00) Abu Dhabi, Muscat',
        value: 'Arabian Standard Time',
    },
    {
        abbr: 'ADT',
        offset: 5,
        isdst: true,
        utc: ['Asia/Baku'],
        ru_names: ['Баку, Азербайджан'],
        text: '(UTC+04:00) Baku',
        value: 'Azerbaijan Standard Time',
    },
    {
        abbr: 'MST',
        offset: 4,
        isdst: false,
        utc: ['Indian/Mahe', 'Indian/Mauritius', 'Indian/Reunion'],
        ru_names: [
            'Порт-Луи, Маврикий',
            'Сен-Дени, Реюньон',
            'Виктория (Сейшели), Сейшельские острова',
        ],
        text: '(UTC+04:00) Port Louis',
        value: 'Mauritius Standard Time',
    },
    {
        abbr: 'GST',
        offset: 4,
        isdst: false,
        utc: ['Asia/Tbilisi'],
        ru_names: ['Тбилиси, Грузия'],
        text: '(UTC+04:00) Tbilisi',
        value: 'Georgian Standard Time',
    },
    {
        abbr: 'CST',
        offset: 4,
        isdst: false,
        utc: ['Asia/Yerevan'],
        ru_names: ['Ереван, Армения'],
        text: '(UTC+04:00) Yerevan',
        value: 'Caucasus Standard Time',
    },
    {
        abbr: 'AST',
        offset: 4.5,
        isdst: false,
        utc: ['Asia/Kabul'],
        ru_names: ['Кабул, Афганистан'],
        text: '(UTC+04:30) Kabul',
        value: 'Afghanistan Standard Time',
    },
    {
        abbr: 'WAST',
        offset: 5,
        isdst: false,
        utc: [
            'Antarctica/Mawson',
            'Asia/Aqtau',
            'Asia/Aqtobe',
            'Asia/Ashgabat',
            'Asia/Dushanbe',
            'Asia/Oral',
            'Asia/Samarkand',
            'Asia/Tashkent',
            'Etc/GMT-5',
            'Indian/Kerguelen',
            'Indian/Maldives',
        ],
        ru_names: [
            'Порт-о-Франс, Французские Южные и Антарктические территории',
            'Актау, Казахстан',
            'Актюбинск, Казахстан',
            'Ашхабад, Туркменистан',
            'Мале, Мальдивы',
            'Ташкент, Узбекистан',
            'Душанбе, Таджикистан',
        ],
        text: '(UTC+05:00) Ashgabat, Tashkent',
        value: 'West Asia Standard Time',
    },
    {
        abbr: 'YEKT',
        offset: 5,
        isdst: false,
        utc: ['Asia/Yekaterinburg'],
        ru_names: [
            'Пермь, Россия',
            'Челябинск, Россия',
            'Уфа, Россия',
            'Екатеринбург, Россия',
        ],
        text: '(UTC+05:00) Yekaterinburg',
        value: 'Yekaterinburg Time',
    },
    {
        abbr: 'PKT',
        offset: 5,
        isdst: false,
        utc: ['Asia/Karachi'],
        ru_names: [
            'Исламабад, Пакистан',
            'Карачи, Пакистан',
            'Лахор, Пакистан',
            'Фейсалабад, Пакистан',
        ],
        text: '(UTC+05:00) Islamabad, Karachi',
        value: 'Pakistan Standard Time',
    },
    {
        abbr: 'IST',
        offset: 5.5,
        isdst: false,
        utc: ['Asia/Kolkata'],
        ru_names: [
            'Патна, Индия',
            'Агра, Индия',
            'Ахмадабад, Индия',
            'Хайдарабад, Индия',
            'Индоре, Индия',
            'Джайпур, Индия',
            'Пуна, Индия',
            'Канпур, Индия',
            'Бангалор, Индия',
            'Колката, Индия',
            'Бхубанешвар, Индия',
            'Лакхнау, Индия',
            'Лудхияна, Индия',
            'Мадурай, Индия',
            'Сурат, Индия',
            'Ченнаи, Индия',
            'Дели, Индия',
            'Вадодара, Индия',
            'Мумбаи, Индия',
            'Варанаси, Индия',
            'Нагпур, Индия',
            'Нью-Дели, Индия',
            'Вишакхапатнам, Индия',
        ],
        text: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
        value: 'India Standard Time',
    },
    {
        abbr: 'SLST',
        offset: 5.5,
        isdst: false,
        utc: ['Asia/Colombo'],
        ru_names: ['Коломбо, Шри-Ланка'],
        text: '(UTC+05:30) Sri Jayawardenepura',
        value: 'Sri Lanka Standard Time',
    },
    {
        abbr: 'NST',
        offset: 5.75,
        isdst: false,
        utc: ['Asia/Katmandu'],
        ru_names: [],
        text: '(UTC+05:45) Kathmandu',
        value: 'Nepal Standard Time',
    },
    {
        abbr: 'CAST',
        offset: 6,
        isdst: false,
        utc: [
            'Antarctica/Vostok',
            'Asia/Almaty',
            'Asia/Bishkek',
            'Asia/Qyzylorda',
            'Asia/Urumqi',
            'Etc/GMT-6',
            'Indian/Chagos',
        ],
        ru_names: [
            'Алма-Ата, Казахстан',
            'Астана, Казахстан',
            'Бишкек, Кыргызстан',
        ],
        text: '(UTC+06:00) Astana',
        value: 'Central Asia Standard Time',
    },
    {
        abbr: 'BST',
        offset: 6,
        isdst: false,
        utc: ['Asia/Dhaka', 'Asia/Thimphu'],
        ru_names: [
            'Кхулна, Бангладеш',
            'Читтагонг, Бангладеш',
            'Тхимпху, Бутан',
            'Дакка, Бангладеш',
        ],
        text: '(UTC+06:00) Dhaka',
        value: 'Bangladesh Standard Time',
    },
    {
        abbr: 'MST',
        offset: 6.5,
        isdst: false,
        utc: ['Asia/Rangoon', 'Indian/Cocos'],
        ru_names: ['Рангун, Мянма'],
        text: '(UTC+06:30) Yangon (Rangoon)',
        value: 'Myanmar Standard Time',
    },
    {
        abbr: 'SAST',
        offset: 7,
        isdst: false,
        utc: [
            'Antarctica/Davis',
            'Asia/Bangkok',
            'Asia/Hovd',
            'Asia/Jakarta',
            'Asia/Phnom_Penh',
            'Asia/Pontianak',
            'Asia/Saigon',
            'Asia/Vientiane',
            'Etc/GMT-7',
            'Indian/Christmas',
        ],
        ru_names: [
            'Палембанг, Индонезия',
            'Кобдо, Монголия',
            'Пномпень, Камбоджа',
            'Джакарта, Индонезия',
            'Кхон Кен, Таиланд',
            'Бандунг, Индонезия',
            'Бангкок, Таиланд',
            'Семаранг, Индонезия',
            'Сурабая, Индонезия',
            'Сухарта, Индонезия',
            'Маланг, Индонезия',
            'Медан, Индонезия',
            'Флайинг-Фиш-Коув, Австралия',
            'Вьентьян, Лаос',
        ],
        text: '(UTC+07:00) Bangkok, Hanoi, Jakarta',
        value: 'SE Asia Standard Time',
    },
    {
        abbr: 'NCAST',
        offset: 7,
        isdst: false,
        utc: ['Asia/Novokuznetsk', 'Asia/Novosibirsk', 'Asia/Omsk'],
        ru_names: ['Новосибирск, Россия', 'Омск, Россия'],
        text: '(UTC+07:00) Novosibirsk',
        value: 'N. Central Asia Standard Time',
    },
    {
        abbr: 'CST',
        offset: 8,
        isdst: false,
        utc: ['Asia/Hong_Kong', 'Asia/Macau', 'Asia/Shanghai'],
        ru_names: [
            'Харбин, Китай',
            'Гонконг, Китай',
            'Аншан, Китай',
            'Цзилинь, Китай',
            'Цзинан, Китай',
            'Цзиньчжоу, Китай',
            'Цицикар, Китай',
            'Баотоу, Китай',
            'Пекин, Китай',
            'Коулун, Китай',
            'Куньмин, Китай',
            'Ланьчжоу, Китай',
            'Лхаса, Китай',
            'Шанхай, Китай',
            'Шитячжуан, Китай',
            'Сиан, Китай',
            'Гуанчжоу, Китай',
            'Далянь, Китай',
            'Лоян, Китай',
            'Чанчунь, Китай',
            'Чанша, Китай',
            'Макао, Китай',
            'Чэнду, Китай',
            'Чунцин, Китай',
            'Тайюань, Китай',
            'Таншань, Китай',
            'Тяньцзинь, Китай',
            'Циндао, Китай',
            'Фучжоу, Китай',
            'Наньчан, Китай',
            'Фушунь, Китай',
            'Ухань, Китай',
            'Гуйян, Китай',
            'Чженчжоу, Китай',
            'Ханчжоу, Китай',
            'Цзыбо, Китай',
        ],
        text: '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
        value: 'China Standard Time',
    },
    {
        abbr: 'NAST',
        offset: 8,
        isdst: false,
        utc: ['Asia/Krasnoyarsk'],
        ru_names: ['Красноярск, Россия'],
        text: '(UTC+08:00) Krasnoyarsk',
        value: 'North Asia Standard Time',
    },
    {
        abbr: 'MPST',
        offset: 8,
        isdst: false,
        utc: [
            'Asia/Brunei',
            'Asia/Kuala_Lumpur',
            'Asia/Kuching',
            'Asia/Makassar',
            'Asia/Manila',
            'Asia/Singapore',
            'Etc/GMT-8',
        ],
        ru_names: [
            'Раба, Индонезия',
            'Баликпапан, Индонезия',
            'Бандар-Сери-Бегаван, Бруней',
            'Куала-Лумпур, Малайзия',
            'Купанг, Индонезия',
            'Сингапур, Сингапур',
            'Сингараджа, Индонезия',
            'Манадо, Индонезия',
            'Манила, Филиппины',
            'Матарам, Индонезия',
            'Денпасар, Индонезия',
            'Энде, Индонезия',
        ],
        text: '(UTC+08:00) Kuala Lumpur, Singapore',
        value: 'Singapore Standard Time',
    },
    {
        abbr: 'WAST',
        offset: 8,
        isdst: false,
        utc: ['Antarctica/Casey', 'Australia/Perth'],
        ru_names: ['Перт, Австралия'],
        text: '(UTC+08:00) Perth',
        value: 'W. Australia Standard Time',
    },
    {
        abbr: 'TST',
        offset: 8,
        isdst: false,
        utc: ['Asia/Taipei'],
        ru_names: ['Гаосюн, Тайвань', 'Тайбэй, Тайвань'],
        text: '(UTC+08:00) Taipei',
        value: 'Taipei Standard Time',
    },
    {
        abbr: 'UST',
        offset: 8,
        isdst: false,
        utc: ['Asia/Choibalsan', 'Asia/Ulaanbaatar'],
        ru_names: ['Чойбалсан, Монголия', 'Улан-Батор, Монголия'],
        text: '(UTC+08:00) Ulaanbaatar',
        value: 'Ulaanbaatar Standard Time',
    },
    {
        abbr: 'NAEST',
        offset: 9,
        isdst: false,
        utc: ['Asia/Irkutsk'],
        ru_names: ['Иркутск, Россия'],
        text: '(UTC+09:00) Irkutsk',
        value: 'North Asia East Standard Time',
    },
    {
        abbr: 'JST',
        offset: 9,
        isdst: false,
        utc: [
            'Asia/Dili',
            'Asia/Jayapura',
            'Asia/Tokyo',
            'Etc/GMT-9',
            'Pacific/Palau',
        ],
        ru_names: [
            'Хиросима, Япония',
            'Амбон, Индонезия',
            'Джаяпура, Индонезия',
            'Кавасаки, Япония',
            'Китакюсю, Япония',
            'Кобе, Япония',
            'Корор, острова Палау',
            'Киото, Япония',
            'Саппоро, Япония',
            'Сендай, Япония',
            'Тернате, Индонезия',
            'Токио, Япония',
            'Дили, Восточный Тимор',
            'Нагоя, Япония',
            'Фукуока, Япония',
            'Окаяма, Япония',
            'Иокогама, Япония',
            'Осака, Япония',
        ],
        text: '(UTC+09:00) Osaka, Sapporo, Tokyo',
        value: 'Japan Standard Time',
    },
    {
        abbr: 'KST',
        offset: 9,
        isdst: false,
        utc: ['Asia/Pyongyang', 'Asia/Seoul'],
        ru_names: [
            'Инчхон, Южная Корея',
            'Бусан, Южная Корея',
            'Пхеньян, Северная Корея',
            'Сеул, Южная Корея',
            'Тэгу, Южная Корея',
        ],
        text: '(UTC+09:00) Seoul',
        value: 'Korea Standard Time',
    },
    {
        abbr: 'CAST',
        offset: 9.5,
        isdst: false,
        utc: ['Australia/Adelaide', 'Australia/Broken_Hill'],
        ru_names: ['Аделаида, Австралия'],
        text: '(UTC+09:30) Adelaide',
        value: 'Cen. Australia Standard Time',
    },
    {
        abbr: 'ACST',
        offset: 9.5,
        isdst: false,
        utc: ['Australia/Darwin'],
        ru_names: ['Дарвин, Австралия'],
        text: '(UTC+09:30) Darwin',
        value: 'AUS Central Standard Time',
    },
    {
        abbr: 'EAST',
        offset: 10,
        isdst: false,
        utc: ['Australia/Brisbane', 'Australia/Lindeman'],
        ru_names: ['Брисбен, Австралия'],
        text: '(UTC+10:00) Brisbane',
        value: 'E. Australia Standard Time',
    },
    {
        abbr: 'AEST',
        offset: 10,
        isdst: false,
        utc: ['Australia/Melbourne', 'Australia/Sydney'],
        ru_names: [
            'Канберра, Австралия',
            'Сидней, Австралия',
            'Мельбурн, Австралия',
        ],
        text: '(UTC+10:00) Canberra, Melbourne, Sydney',
        value: 'AUS Eastern Standard Time',
    },
    {
        abbr: 'WPST',
        offset: 10,
        isdst: false,
        utc: [
            'Antarctica/DumontDUrville',
            'Etc/GMT-10',
            'Pacific/Guam',
            'Pacific/Port_Moresby',
            'Pacific/Saipan',
            'Pacific/Truk',
        ],
        ru_names: [
            'Порт-Морсби, Папуа-Новая Гвинея',
            'Сайпан, Содружество Северных Марианских островов',
            'Гуам, Соединенные Штаты Америки (США)',
        ],
        text: '(UTC+10:00) Guam, Port Moresby',
        value: 'West Pacific Standard Time',
    },
    {
        abbr: 'TST',
        offset: 10,
        isdst: false,
        utc: ['Australia/Currie', 'Australia/Hobart'],
        ru_names: ['Хобарт, Австралия'],
        text: '(UTC+10:00) Hobart',
        value: 'Tasmania Standard Time',
    },
    {
        abbr: 'YST',
        offset: 10,
        isdst: false,
        utc: ['Asia/Chita', 'Asia/Khandyga', 'Asia/Yakutsk'],
        ru_names: ['Якутск, Россия'],
        text: '(UTC+10:00) Yakutsk',
        value: 'Yakutsk Standard Time',
    },
    {
        abbr: 'CPST',
        offset: 11,
        isdst: false,
        utc: [
            'Antarctica/Macquarie',
            'Etc/GMT-11',
            'Pacific/Efate',
            'Pacific/Guadalcanal',
            'Pacific/Kosrae',
            'Pacific/Noumea',
            'Pacific/Ponape',
        ],
        ru_names: [
            'Хониара, Соломоновы острова',
            'Порт Вила, Вануату',
            'Нумеа, Новая Каледония',
        ],
        text: '(UTC+11:00) Solomon Is., New Caledonia',
        value: 'Central Pacific Standard Time',
    },
    {
        abbr: 'VST',
        offset: 11,
        isdst: false,
        utc: ['Asia/Sakhalin', 'Asia/Ust-Nera', 'Asia/Vladivostok'],
        ru_names: ['Владивосток, Россия'],
        text: '(UTC+11:00) Vladivostok',
        value: 'Vladivostok Standard Time',
    },
    {
        abbr: 'NZST',
        offset: 12,
        isdst: false,
        utc: ['Antarctica/McMurdo', 'Pacific/Auckland'],
        ru_names: [
            'Окленд, Новая Зеландия',
            'Крайстчерч, Новая Зеландия',
            'Веллингтон, Новая Зеландия',
        ],
        text: '(UTC+12:00) Auckland, Wellington',
        value: 'New Zealand Standard Time',
    },
    {
        abbr: 'U',
        offset: 12,
        isdst: false,
        utc: [
            'Etc/GMT-12',
            'Pacific/Funafuti',
            'Pacific/Kwajalein',
            'Pacific/Majuro',
            'Pacific/Nauru',
            'Pacific/Tarawa',
            'Pacific/Wake',
            'Pacific/Wallis',
        ],
        ru_names: [
            'Маджуро, Маршаловы острова',
            'Ярен, Науру',
            'Баірікі, Кирибати',
            'Фунафути, Тувалу',
        ],
        text: '(UTC+12:00) Coordinated Universal Time+12',
        value: 'UTC+12',
    },
    {
        abbr: 'FST',
        offset: 12,
        isdst: false,
        utc: ['Pacific/Fiji'],
        ru_names: ['Сува, Фиджи'],
        text: '(UTC+12:00) Fiji',
        value: 'Fiji Standard Time',
    },
    {
        abbr: 'MST',
        offset: 12,
        isdst: false,
        utc: [
            'Asia/Anadyr',
            'Asia/Kamchatka',
            'Asia/Magadan',
            'Asia/Srednekolymsk',
        ],
        ru_names: ['Анадырь, Россия', 'Петропавловск-Камчатский, Россия'],
        text: '(UTC+12:00) Magadan',
        value: 'Magadan Standard Time',
    },
    {
        abbr: 'KDT',
        offset: 13,
        isdst: true,
        utc: ['Asia/Kamchatka'],
        ru_names: ['Петропавловск-Камчатский, Россия'],
        text: '(UTC+12:00) Petropavlovsk-Kamchatsky - Old',
        value: 'Kamchatka Standard Time',
    },
    {
        abbr: 'TST',
        offset: 13,
        isdst: false,
        utc: [
            'Etc/GMT-13',
            'Pacific/Enderbury',
            'Pacific/Fakaofo',
            'Pacific/Tongatapu',
        ],
        ru_names: ['Раваки, Кирибати', 'Нукуалофа, Тонга'],
        text: "(UTC+13:00) Nuku'alofa",
        value: 'Tonga Standard Time',
    },
    {
        abbr: 'SST',
        offset: 13,
        isdst: false,
        utc: ['Pacific/Apia'],
        ru_names: ['Апиа, Самоа'],
        text: '(UTC+13:00) Samoa',
        value: 'Samoa Standard Time',
    },
];
